# Generated by Django 5.2 on 2026-03-06 12:13

import apps.sharing.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0003_add_visibility_and_saved'),
        ('reviews', '0009_alter_wanttotry_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('target_count', models.PositiveIntegerField(default=5)),
                ('cuisine_filter', models.CharField(blank=True, default='', max_length=100)),
                ('tag_filter', models.CharField(blank=True, default='', max_length=100)),
                ('xp_reward', models.PositiveIntegerField(default=500)),
                ('badge_slug', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenges',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reward_claimed', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='sharing.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_participants',
            },
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('verification_notes', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='sharing.challengeparticipant')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_submissions', to='reviews.review')),
            ],
            options={
                'db_table': 'challenge_submissions',
            },
        ),
        migrations.CreateModel(
            name='DeferredDeepLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('target_path', models.CharField(max_length=500)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('utm_source', models.CharField(blank=True, default='', max_length=100)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=100)),
                ('invite_code', models.CharField(blank=True, default='', max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deep_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deferred_deep_links',
            },
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=apps.sharing.models.generate_invite_code, max_length=20, unique=True)),
                ('max_uses', models.PositiveIntegerField(default=100)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invite_codes',
            },
        ),
        migrations.CreateModel(
            name='PlaylistActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('item_added', 'Item Added'), ('item_removed', 'Item Removed'), ('comment', 'Comment'), ('collaborator_added', 'Collaborator Added')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='playlists.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'playlist_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='playlists.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'playlist_collaborators',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('signed_up', 'Signed Up'), ('activated', 'Activated'), ('churned', 'Churned')], default='signed_up', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('invite_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharing.invitecode')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referrals',
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reward_type', models.CharField(choices=[('xp_bonus', 'XP Bonus'), ('badge', 'Badge'), ('premium_trial', 'Premium Trial')], max_length=20)),
                ('tier', models.CharField(choices=[('tier_1', '3 Referrals'), ('tier_2', '10 Referrals'), ('tier_3', '25 Referrals')], max_length=10)),
                ('reward_value', models.PositiveIntegerField(default=0)),
                ('claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referral_rewards',
            },
        ),
        migrations.CreateModel(
            name='ShareCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('review', 'Review'), ('venue', 'Venue'), ('playlist', 'Playlist'), ('profile', 'Profile'), ('wrapped', 'Wrapped')], max_length=20)),
                ('platform', models.CharField(choices=[('ig_story', 'Instagram Story'), ('ig_feed', 'Instagram Feed'), ('twitter', 'Twitter'), ('og', 'Open Graph')], max_length=20)),
                ('related_object_id', models.UUIDField()),
                ('image_url', models.URLField(max_length=500)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'share_cards',
                'indexes': [models.Index(fields=['card_type', 'platform', 'related_object_id'], name='idx_sharecard_lookup')],
            },
        ),
        migrations.AddIndex(
            model_name='challengeparticipant',
            index=models.Index(fields=['challenge', '-progress'], name='idx_challenge_progress'),
        ),
        migrations.AddConstraint(
            model_name='challengeparticipant',
            constraint=models.UniqueConstraint(fields=('challenge', 'user'), name='uq_challenge_participant'),
        ),
        migrations.AddConstraint(
            model_name='challengesubmission',
            constraint=models.UniqueConstraint(fields=('participant', 'review'), name='uq_challenge_submission'),
        ),
        migrations.AddIndex(
            model_name='deferreddeeplink',
            index=models.Index(fields=['fingerprint'], name='idx_deeplink_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='playlistcollaborator',
            constraint=models.UniqueConstraint(fields=('playlist', 'user'), name='uq_playlist_collaborator'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(fields=('invitee',), name='uq_invitee'),
        ),
        migrations.AddConstraint(
            model_name='referralreward',
            constraint=models.UniqueConstraint(fields=('user', 'reward_type', 'tier'), name='uq_referral_reward'),
        ),
    ]
