# Generated by Django 5.2 on 2026-03-05 17:34

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        ('venues', '0003_backfill_dishes_from_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('likes_enabled', models.BooleanField(default=True)),
                ('comments_enabled', models.BooleanField(default=True)),
                ('follows_enabled', models.BooleanField(default=True)),
                ('mentions_enabled', models.BooleanField(default=True)),
                ('trending_enabled', models.BooleanField(default=True)),
                ('streaks_enabled', models.BooleanField(default=True)),
                ('badges_enabled', models.BooleanField(default=True)),
                ('nudges_enabled', models.BooleanField(default=True)),
                ('digest_enabled', models.BooleanField(default=True)),
                ('nearby_enabled', models.BooleanField(default=True)),
                ('social_frequency', models.CharField(choices=[('instant', 'Instant'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('never', 'Never')], default='instant', max_length=10)),
                ('digest_frequency', models.CharField(choices=[('instant', 'Instant'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('never', 'Never')], default='weekly', max_length=10)),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(default=datetime.time(22, 0))),
                ('quiet_hours_end', models.TimeField(default=datetime.time(8, 0))),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='VenueSaveReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('trigger_after', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'venue_save_reminders',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='bundle_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-App'), ('push', 'Push'), ('email', 'Email'), ('sms', 'SMS')], default='in_app', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='group_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_bundled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('playlist_add', 'Playlist Add'), ('mention', 'Mention'), ('trending', 'Trending'), ('streak', 'Streak'), ('badge', 'Badge'), ('nudge', 'Nudge'), ('digest', 'Digest'), ('level_up', 'Level Up'), ('nearby', 'Nearby Venue')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'group_key', '-created_at'], name='idx_notification_bundle'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for'], name='idx_notification_scheduled'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venuesavereminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venuesavereminder',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_reminders', to='venues.venue'),
        ),
        migrations.AddConstraint(
            model_name='venuesavereminder',
            constraint=models.UniqueConstraint(fields=('user', 'venue'), name='uq_venue_save_reminder'),
        ),
    ]
