# Generated by Django 5.2 on 2026-03-04 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasteMatchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('shared_venues', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taste_matches_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taste_matches_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'taste_match_cache',
                'constraints': [models.UniqueConstraint(fields=('user_a', 'user_b'), name='uq_taste_match_pair')],
            },
        ),
    ]
