# Generated by Django 5.2 on 2026-03-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tastematchcache'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following'], name='idx_follow_following'),
        ),
    ]
