# Generated by Django 5.2 on 2026-02-27 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('location_text', models.CharField(blank=True, default='', max_length=500)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('cuisine_type', models.CharField(blank=True, default='', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('photo_url', models.URLField(blank=True, default='', max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_place_id', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'venues',
                'ordering': ['-rating'],
                'indexes': [models.Index(fields=['cuisine_type', '-rating'], name='idx_venue_cuisine_rating')],
            },
        ),
    ]
