# Generated by Django 5.2 on 2026-03-05 09:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OccasionTag',
            fields=[
                ('slug', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=8)),
                ('category', models.CharField(choices=[('social', 'Social'), ('time', 'Time'), ('vibe', 'Vibe')], max_length=20)),
            ],
            options={
                'db_table': 'occasion_tags',
                'ordering': ['category', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, choices=[('appetizer', 'Appetizer'), ('main', 'Main'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('side', 'Side'), ('other', 'Other')], max_length=50)),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='venues.venue')),
            ],
            options={
                'db_table': 'dishes',
                'ordering': ['-review_count'],
                'unique_together': {('venue', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DietaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('gluten-free', 'Gluten Free'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('dairy-free', 'Dairy Free'), ('nut-free', 'Nut Free')], max_length=30)),
                ('scope', models.CharField(choices=[('venue', 'Venue'), ('dish', 'Dish')], default='venue', max_length=20)),
                ('is_available', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_reports', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_reports', to='venues.venue')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dietary_reports', to='venues.dish')),
            ],
            options={
                'db_table': 'dietary_reports',
                'constraints': [models.UniqueConstraint(fields=('user', 'venue', 'category', 'scope'), name='uq_dietary_report_user_venue_cat_scope')],
            },
        ),
        migrations.CreateModel(
            name='OccasionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.occasiontag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occasion_votes', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venue')),
            ],
            options={
                'db_table': 'occasion_votes',
                'constraints': [models.UniqueConstraint(fields=('user', 'venue', 'occasion'), name='uq_occasion_vote_user_venue_occasion')],
            },
        ),
        migrations.CreateModel(
            name='VenueOccasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.occasiontag')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occasions', to='venues.venue')),
            ],
            options={
                'db_table': 'venue_occasions',
                'ordering': ['-vote_count'],
                'unique_together': {('venue', 'occasion')},
            },
        ),
        migrations.CreateModel(
            name='VenueSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('venue_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_a', to='venues.venue')),
                ('venue_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_b', to='venues.venue')),
            ],
            options={
                'db_table': 'venue_similarities',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['venue_a', '-score'], name='idx_similarity_a_score')],
                'constraints': [models.UniqueConstraint(fields=('venue_a', 'venue_b'), name='uq_venue_similarity_pair')],
            },
        ),
    ]
