# Generated by Django 5.2 on 2026-03-06 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_venue_price_level_venueowner_venueresponse_kitchenstory_foodguide_guidestop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dietaryreport',
            index=models.Index(fields=['venue', 'category'], name='idx_dietaryreport_venue_cat'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['venue'], name='idx_dish_venue'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['-rating'], name='idx_venue_rating_desc'),
        ),
        migrations.AddIndex(
            model_name='venueoccasion',
            index=models.Index(fields=['venue'], name='idx_venueoccasion_venue'),
        ),
    ]
