# Generated by Django 5.2 on 2026-03-17 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_dietaryreport_idx_dietaryreport_venue_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueRatingSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_type', models.CharField(choices=[('week', 'Week'), ('month', 'Month')], default='month', max_length=10)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('min_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('max_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_snapshots', to='venues.dish')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_snapshots', to='venues.venue')),
            ],
            options={
                'db_table': 'venue_rating_snapshots',
                'ordering': ['period_start'],
                'indexes': [models.Index(fields=['venue', 'period_start'], name='idx_snapshot_venue_period'), models.Index(fields=['dish', 'period_start'], name='idx_snapshot_dish_period')],
                'constraints': [models.UniqueConstraint(fields=('venue', 'dish', 'period_start', 'period_type'), name='uq_rating_snapshot_venue_dish_period')],
            },
        ),
    ]
