# Generated by Django 5.2 on 2026-03-06 01:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('explorer', 'Explorer'), ('foodie', 'Foodie'), ('social', 'Social'), ('streak', 'Streak'), ('photographer', 'Photographer'), ('curator', 'Curator'), ('reviewer', 'Reviewer'), ('local', 'Local Expert')], max_length=20)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=10)),
                ('icon_url', models.URLField(blank=True, default='', max_length=500)),
                ('requirement_type', models.CharField(max_length=50)),
                ('requirement_value', models.PositiveIntegerField()),
                ('xp_reward', models.PositiveIntegerField(default=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'badge_definitions',
                'ordering': ['category', 'tier', 'requirement_value'],
            },
        ),
        migrations.CreateModel(
            name='DiningStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('streak_freezes', models.PositiveIntegerField(default=0)),
                ('max_freezes', models.PositiveIntegerField(default=2)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('grace_hours', models.PositiveIntegerField(default=4)),
                ('flexible_mode', models.BooleanField(default=False)),
                ('weekly_activity_count', models.PositiveIntegerField(default=0)),
                ('week_start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dining_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dining_streaks',
            },
        ),
        migrations.CreateModel(
            name='UserStatsCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_venues', models.PositiveIntegerField(default=0)),
                ('total_photos', models.PositiveIntegerField(default=0)),
                ('total_likes_given', models.PositiveIntegerField(default=0)),
                ('total_likes_received', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('favorite_cuisine', models.CharField(blank=True, default='', max_length=100)),
                ('review_this_week', models.PositiveIntegerField(default=0)),
                ('review_this_month', models.PositiveIntegerField(default=0)),
                ('last_refreshed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_stats_cache',
            },
        ),
        migrations.CreateModel(
            name='UserXP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp_to_next_level', models.PositiveIntegerField(default=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_xp',
            },
        ),
        migrations.CreateModel(
            name='ActivityDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('photo_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_days',
                'indexes': [models.Index(fields=['user', '-date'], name='idx_activity_user_date')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uq_activity_day')],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('board_type', models.CharField(choices=[('global', 'Global'), ('city', 'City'), ('friends', 'Friends'), ('cuisine', 'Cuisine')], max_length=10)),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=10)),
                ('scope', models.CharField(blank=True, default='', max_length=100)),
                ('score', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaderboard_entries',
                'indexes': [models.Index(fields=['board_type', 'period', 'scope', '-score'], name='idx_leaderboard')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('is_displayed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='gamification.badgedefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_badges',
                'indexes': [models.Index(fields=['user', 'is_unlocked'], name='idx_badge_user')],
                'constraints': [models.UniqueConstraint(fields=('user', 'badge'), name='uq_user_badge')],
            },
        ),
        migrations.CreateModel(
            name='WrappedStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_venues', models.PositiveIntegerField(default=0)),
                ('total_photos', models.PositiveIntegerField(default=0)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('levels_gained', models.PositiveIntegerField(default=0)),
                ('badges_earned', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('top_cuisine', models.CharField(blank=True, default='', max_length=100)),
                ('top_venue', models.CharField(blank=True, default='', max_length=200)),
                ('top_venue_visits', models.PositiveIntegerField(default=0)),
                ('total_likes_received', models.PositiveIntegerField(default=0)),
                ('total_comments_received', models.PositiveIntegerField(default=0)),
                ('new_followers', models.PositiveIntegerField(default=0)),
                ('stats_data', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrapped_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wrapped_stats',
                'constraints': [models.UniqueConstraint(fields=('user', 'year'), name='uq_wrapped_year')],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('review', 'Posted Review'), ('review_photo', 'Photo with Review'), ('comment', 'Posted Comment'), ('like_given', 'Liked Review'), ('like_received', 'Received Like'), ('streak', 'Streak Bonus'), ('badge', 'Badge Earned'), ('level_up', 'Level Up Bonus'), ('first_review', 'First Review Bonus'), ('referral', 'Referral Bonus')], max_length=20)),
                ('amount', models.IntegerField()),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'xp_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_xp_user')],
            },
        ),
    ]
