# Generated by Django 5.2 on 2026-03-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_bookmark_comment_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='quality_score',
            field=models.FloatField(default=0.0),
        ),
    ]
