# Generated by Django 5.2 on 2026-03-05 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_quality_score'),
        ('venues', '0002_occasiontag_dish_dietaryreport_occasionvote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='chk_comment_parent_valid',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='uq_review_user_venue',
        ),
        migrations.AddField(
            model_name='review',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='venues.dish'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('dish__isnull', True)), fields=('user', 'venue'), name='uq_review_user_venue_no_dish'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('dish__isnull', False)), fields=('user', 'venue', 'dish'), name='uq_review_user_venue_dish'),
        ),
    ]
