# Generated by Django 5.2 on 2026-03-05 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_comment_chk_comment_parent_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), ('parent__isnull', False), _connector='OR'), name='chk_comment_parent_valid'),
        ),
    ]
