# Generated by Django 5.2 on 2026-03-06 01:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_comment_chk_comment_parent_valid'),
        ('venues', '0003_backfill_dishes_from_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_url', models.URLField(max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'review_photos',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at', '-like_count'], name='idx_review_feed'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['venue', '-created_at'], name='idx_review_venue_date'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at', '-like_count'], name='idx_review_trending'),
        ),
        migrations.AddField(
            model_name='reviewphoto',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reviews.review'),
        ),
        migrations.AddIndex(
            model_name='reviewphoto',
            index=models.Index(fields=['review', 'sort_order'], name='idx_reviewphoto_review'),
        ),
    ]
