# Generated by Django 5.2 on 2026-03-06 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_wanttotry'),
        ('venues', '0005_venue_price_level_venueowner_venueresponse_kitchenstory_foodguide_guidestop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wanttotry',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='wanttotry',
            constraint=models.UniqueConstraint(fields=('user', 'venue'), name='uq_want_to_try_user_venue'),
        ),
    ]
