# Generated by Django 5.2 on 2026-03-06 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_wanttotry_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user'], name='idx_bookmark_user'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='idx_comment_user'),
        ),
        migrations.AddIndex(
            model_name='reviewlike',
            index=models.Index(fields=['user'], name='idx_reviewlike_user'),
        ),
    ]
