# Generated by Django 5.2

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0010_bookmark_idx_bookmark_user_comment_idx_comment_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("inappropriate", "Inappropriate Content"),
                            ("harassment", "Harassment"),
                            ("false_info", "False Information"),
                            ("copyright", "Copyright Violation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("review", "Review"),
                            ("comment", "Comment"),
                            ("user", "User Profile"),
                            ("photo", "Photo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_id", models.UUIDField()),
                (
                    "reason",
                    models.TextField(blank=True, default="", max_length=500),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("actioned", "Action Taken"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "action_taken",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "content_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.UniqueConstraint(
                fields=("reporter", "content_type", "content_id"),
                name="unique_report_per_user_per_content",
            ),
        ),
    ]
