# Generated by Django 5.2 on 2026-03-06 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0009_alter_wanttotry_unique_together_and_more'),
        ('venues', '0005_venue_price_level_venueowner_venueresponse_kitchenstory_foodguide_guidestop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('authenticity', 'Review Authenticity'), ('ranking', 'Venue Ranking'), ('recommendation', 'Recommendation')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('metrics', models.JSONField(default=dict)),
                ('trained_at', models.DateTimeField()),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ml_model_metadata',
                'constraints': [models.UniqueConstraint(fields=('model_type', 'version'), name='uq_ml_model')],
            },
        ),
        migrations.CreateModel(
            name='ReviewAuthenticity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authenticity_score', models.FloatField(default=0.5)),
                ('is_trusted', models.BooleanField(default=True)),
                ('flags', models.JSONField(default=list)),
                ('model_version', models.CharField(default='v1', max_length=50)),
                ('scored_at', models.DateTimeField(auto_now=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authenticity', to='reviews.review')),
            ],
            options={
                'db_table': 'review_authenticity',
            },
        ),
        migrations.CreateModel(
            name='TrendingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('venue', 'Venue'), ('dish', 'Dish'), ('cuisine', 'Cuisine')], max_length=20)),
                ('item_id', models.UUIDField()),
                ('item_name', models.CharField(max_length=200)),
                ('trend_score', models.FloatField()),
                ('velocity', models.FloatField(default=0)),
                ('explanation', models.CharField(blank=True, default='', max_length=500)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'trending_items',
                'indexes': [models.Index(fields=['item_type', '-trend_score'], name='idx_trending')],
            },
        ),
        migrations.CreateModel(
            name='VenueIngestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('google_places', 'Google Places'), ('yelp', 'Yelp'), ('manual', 'Manual')], max_length=20)),
                ('external_id', models.CharField(max_length=200)),
                ('raw_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestions', to='venues.venue')),
            ],
            options={
                'db_table': 'venue_ingestions',
                'indexes': [models.Index(fields=['processed', '-created_at'], name='idx_ingestion_processed')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uq_venue_ingestion')],
            },
        ),
        migrations.CreateModel(
            name='VenueRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('reason_type', models.CharField(blank=True, default='', max_length=50)),
                ('model_version', models.CharField(default='v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_recommendations', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recommendations', to='venues.venue')),
            ],
            options={
                'db_table': 'venue_recommendations',
                'indexes': [models.Index(fields=['user', '-score'], name='idx_recommendation_user')],
            },
        ),
    ]
