# Generated by Django 5.2 on 2026-03-06 02:05

import apps.groups.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0004_seasonalhighlight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('voting', 'Voting'), ('decided', 'Decided'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('share_code', models.CharField(default=apps.groups.models.generate_share_code, max_length=8, unique=True)),
                ('vote_deadline', models.DateTimeField(blank=True, null=True)),
                ('suggested_date', models.DateField(blank=True, null=True)),
                ('suggested_time', models.TimeField(blank=True, null=True)),
                ('max_venues', models.PositiveIntegerField(default=10)),
                ('cuisine_filter', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dinner_plans', to=settings.AUTH_USER_MODEL)),
                ('selected_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_dinner_plans', to='venues.venue')),
            ],
            options={
                'db_table': 'dinner_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DinnerPlanVenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_yes', models.PositiveIntegerField(default=0)),
                ('total_no', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_options', to='groups.dinnerplan')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_plan_options', to='venues.venue')),
            ],
            options={
                'db_table': 'dinner_plan_venues',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='DinnerPlanVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('skip', 'Skip')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='groups.dinnerplanvenue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_plan_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dinner_plan_votes',
            },
        ),
        migrations.CreateModel(
            name='DinnerPlanMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('host', 'Host'), ('member', 'Member')], default='member', max_length=10)),
                ('has_voted', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.dinnerplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_plan_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dinner_plan_members',
                'constraints': [models.UniqueConstraint(fields=('plan', 'user'), name='uq_dinner_plan_member')],
            },
        ),
        migrations.AddConstraint(
            model_name='dinnerplanvenue',
            constraint=models.UniqueConstraint(fields=('plan', 'venue'), name='uq_dinner_plan_venue'),
        ),
        migrations.AddConstraint(
            model_name='dinnerplanvote',
            constraint=models.UniqueConstraint(fields=('plan_venue', 'user'), name='uq_dinner_plan_vote'),
        ),
    ]
