# Generated by Django 5.2 on 2026-03-04 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTasteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_cuisines', models.JSONField(blank=True, default=list)),
                ('dietary_restrictions', models.JSONField(blank=True, default=list)),
                ('price_preference', models.CharField(choices=[('budget', 'Budget'), ('mid', 'Mid-Range'), ('fine', 'Fine Dining'), ('any', 'Any')], default='any', max_length=20)),
                ('spice_tolerance', models.PositiveSmallIntegerField(default=3)),
                ('completed_wizard', models.BooleanField(default=False)),
                ('maturity_level', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taste_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_taste_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_following', models.BooleanField(default=False)),
                ('interaction_count', models.PositiveIntegerField(default=0)),
                ('has_mutual_follow', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities_as_target', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities_as_viewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_affinity',
                'indexes': [models.Index(fields=['user', '-score'], name='idx_affinity_user_score')],
                'constraints': [models.UniqueConstraint(fields=('user', 'target'), name='uq_user_affinity_pair')],
            },
        ),
        migrations.CreateModel(
            name='VenueTrendingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('review_velocity', models.FloatField(default=0.0)),
                ('z_score', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trending_score', to='venues.venue')),
            ],
            options={
                'db_table': 'venue_trending_scores',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['-score'], name='idx_trending_score')],
            },
        ),
    ]
