# Generated by Django 5.2 on 2026-03-06 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useraffinity',
            index=models.Index(fields=['user', 'updated_at'], name='idx_affinity_user_updated'),
        ),
    ]
